tobiasgg/DD2480-2022-Group-13-Assignment-1

.gitignore, pom.xml, src/Main.java, src/Point.java, src/PreliminaryUnlockingMatrixCalculator.java, src/main/java/Decide/Decide.java, src/main/java/Decide/FinalUnlockingVectorCalculator.java, src/main/java/Decide/LaunchCalculator.java, src/main/java/Decide/LaunchInterceptorConditions.java, src/main/java/Decide/LogicalConnectorOperator.java, src/main/java/Decide/Parameters.java, src/main/java/Decide/Point.java, src/main/java/Decide/PreliminaryUnlockingMatrixCalculator.java, src/test/java/LaunchInterceptorConditionsTest.java
=> feat: updates skeleton and integrates maven

src/main/java/Decide/Decide.java, src/main/java/Decide/LaunchInterceptorConditions.java, src/test/java/LaunchInterceptorConditionsTest.java
Implements LIC0 along with unit tests.
=> feat: Fix issue #3 and issue #18

src/main/java/Decide/LaunchInterceptorConditions.java
=> feat: LIC1 and test cases

src/main/java/Decide/Decide.java, src/main/java/Decide/LaunchInterceptorConditions.java, src/test/java/LaunchInterceptorConditionsTest.java
=> feat: LIC4 and test cases

src/main/java/Decide/Decide.java, src/main/java/Decide/LaunchInterceptorConditions.java, src/test/java/LaunchInterceptorConditionsTest.java
=> feat: LIC2 and test cases

src/main/java/decide/LaunchInterceptorConditions.java, src/test/java/LaunchInterceptorConditionsTest.java
=> feat: LIC6 and test cases

src/main/java/decide/LaunchInterceptorConditions.java, src/test/java/LaunchInterceptorConditionsTest.java
=> feat: LIC7 and test cases

src/main/java/decide/LaunchInterceptorConditions.java, src/test/java/LaunchInterceptorConditionsTest.java
=> feat: LIC9 and test cases

.gitignore, pom.xml
=> fix: sourceDirectory missing in pom.xml

src/main/java/decide/PreliminaryUnlockingMatrixCalculator.java, src/test/java/PreliminaryUnlockingMatrixCalculatorTests.java
=> feat: impl PreliminaryUnlockingMatrixCalculator with tests

src/main/java/decide/LaunchInterceptorConditions.java, src/test/java/LaunchInterceptorConditionsTest.java
=> feat: LIC13 and test cases

src/main/java/decide/FinalUnlockingVectorCalculator.java, src/test/java/FinalUnlockingVectorCalculatorTests.java
=> feat: implement FinalUnlockingVectorCalculator

src/main/java/decide/LaunchCalculator.java, src/test/java/LaunchCalculatorTests.java
=> feat: LaunchCalculator

src/main/java/decide/LaunchInterceptorConditions.java, src/test/java/LaunchInterceptorConditionsTest.java
=> feat: LIC12 and test cases

src/main/java/decide/LaunchInterceptorConditions.java, src/test/java/LaunchInterceptorConditionsTest.java
=> feat: LIC3 and test cases

src/main/java/decide/LaunchInterceptorConditions.java, src/test/java/LaunchInterceptorConditionsTest.java
=> feat: LIC5 with testcases.

src/main/java/decide/LaunchInterceptorConditions.java, src/test/java/LaunchInterceptorConditionsTest.java
=> feat: LIC8 with testcases.

src/main/java/decide/LaunchInterceptorConditions.java, src/test/java/LaunchInterceptorConditionsTest.java
=> feat: LIC10 with testcases.

src/main/java/decide/LaunchInterceptorConditions.java, src/test/java/LaunchInterceptorConditionsTest.java
=> feat: LIC14 with testcases

src/main/java/decide/Point.java
=> Removes the redundant code for the simple class Point.

src/main/java/decide/LaunchInterceptorConditions.java
Added the last assertion that is needed for the LIC8.
fixes #52
=> fix: added assertion for LIC8.

src/main/java/decide/LaunchInterceptorConditions.java
=> fix: necessary assertion added to LIC0

README.md
=> doc: Added a draft for the README

src/main/java/decide/Decide.java
=> fix: Makes Output fields public.

src/main/java/decide/LaunchInterceptorConditions.java, src/test/java/LaunchInterceptorConditionsTest.java
=> fix: added assertion in function and assertThrow in testcase.

README.md
=> docs: added filips contributions to readme

src/test/java/LaunchInterceptorConditionsTest.java
=> fix: Added comments/docs to all testcases.

src/main/java/decide/LaunchInterceptorConditions.java
=> fix: Added comments/documentation to all LIC's.

README.md
=> doc: Adds Siyao's contribution to README

pom.xml, src/main/java/Main.java
=> Adds a Main class to the program for entry point and modified pom.xml accordingly.

README.md
=> doc: add How to use and Way of Working

README.md
=> doc: adds a note to the grader to clarify things

README.md
=> doc: edwin's contribution
